---
##
# Secure database
##
- block:
#  - debug:
#      msg: "Current password now: {{ percona_mysql_root_password }}"

  - name: MYSQL_USER | Remove all anonymous accounts
    community.mysql.mysql_user:
      login_user: root
      login_password: "{{ percona_mysql_root_password }}"
      login_unix_socket: "{{ percona_mysql_config_socket }}"
      name: ''
      host_all: yes
      state: absent

  - name: MYSQL_DB | Remove the MySQL test database
    community.mysql.mysql_db:
      login_user: root
      login_password: "{{ percona_mysql_root_password }}"
      login_unix_socket: "{{ percona_mysql_config_socket }}"
      db: test
      state: absent
    notify: restart mysql

  when: percona_mysql_enabled and percona_mysql_config_server_role == 'master'
