---
#
# Setup all required packages
#
- block:
  - name: APT | Make sure jemalloc package is installed (if configured)
    apt:
      name: "{{ percona_mysql_jemalloc_package }}"
      state: "{{ percona_mysql_packages_mode }}"
    when: percona_mysql_jemalloc_enabled

  - name: COPY | Copy service for disabling huge pages
    copy:
      src: disable-transparent-hugepages.service
      dest: /etc/systemd/system/disable-transparent-hugepages.service
      owner: root
      group: root
      mode: 0644

  - name: TEMPLATE | Apply jemalloc sysconfig mysql template
    template:
      src: "sysconfig.mysql.j2"
      dest: "{{ percona_mysql_jemalloc_sysconfig }}"
      owner: root
      group: root
      mode: 0644
    notify: restart mysql

  - name: LINEINFILE | Switch to malloc implementation
    lineinfile:
      path: "{{ percona_mysql_systemd_service }}"
      regexp: '^EnvironmentFile='
      line: "EnvironmentFile={{ percona_mysql_jemalloc_sysconfig }}"
    notify:
      - daemon reload
      - restart mysql

  - name: SYSTEMD | Reload daemon now
    systemd:
      daemon_reload: yes
    changed_when: False

  - name: SYSTEMD | Enable and start the huge page disabling service
    systemd:
      name: disable-transparent-hugepages
      enabled: yes
      state: started

  when:
    - percona_mysql_enabled
    - percona_mysql_jemalloc_enabled


