---
#
# Setup all required packages
#
- block:
  - name: APT | Updating the apt cache
    apt:
      update_cache: yes

  - name: APT | Install package dependencies
    apt:
      name: "{{ percona_mysql_package_dependencies }}"
      state: present

  - name: APT | Install the Percona MySQL repository
    apt:
      deb: "{{ percona_mysql_repository }}"
    when: percona_mysql_repository is defined

  - name: APT | Updating the apt cache after adding the release repository
    apt:
      update_cache: yes

  - name: COMMAND | Enable the Percona MySQL repository
    command: "{{ percona_mysql_enable_repository }}"
    when: percona_mysql_enable_repository is defined
    changed_when: False

  - name: APT | Ensure MySQL Python libraries are installed.
    apt:
      name: "{{ percona_mysql_python_packages }}"
      state: present

  - name: APT | Install Percona MySQL packages
    apt:
      name: "{{ percona_mysql_packages }}"
      state: "{{ percona_mysql_packages_mode }}"

  - name: SYSCTL | Add settings for sysctl for the server
    sysctl:
      sysctl_set: yes
      reload: yes
      state: present
      name: "{{ item.key }}"
      value: "{{ item.value }}"
    with_dict: "{{ percona_mysql_sysctl_settings }}"
    when: percona_mysql_sysctl_settings is defined and percona_mysql_sysctl_settings != ''

  when: percona_mysql_enabled
